### ISSUE TITLE
Training encounters NaN during valiration

### ISSUE THREAD

**Issue by ziqi-zhang** [goten-team/Goten#2]
Hi, I compiled the code but the validation of the training process encounters NaN value. Here is the log:
```
TrainCounter: 30, current_loss: 2.3025851249694824
TrainCounter: 30, current_loss: 2.3025851249694824
Time for TrainWithBatch: 1155.092477798462 ms
Time for TrainWithBatch: 1156.8808555603027 ms
Process Process-1:
Traceback (most recent call last):
  File "/home/zhangziqi/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/zhangziqi/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhangziqi/Goten/python/vgg.py", line 256, in local_vgg9
    validation_accuracy()
  File "/home/zhangziqi/Goten/python/vgg.py", line 171, in validation_accuracy
    outputs = validation_net(images)
  File "/home/zhangziqi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangziqi/Goten/python/quantize_net.py", line 447, in forward
    return self.forward_with_bn(x)
  File "/home/zhangziqi/Goten/python/quantize_net.py", line 432, in forward_with_bn
    x = self.pool(F.relu(self.norm1(self.conv1(x))))
  File "/home/zhangziqi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangziqi/Goten/python/quantize_net.py", line 245, in forward
    return QuantizeConv2dFunction.apply(input, self.weight, self.bias, self.layer_name, self.iter_time)
  File "/home/zhangziqi/Goten/python/quantize_net.py", line 179, in forward
    InputQ, WeightQ = pre_quantize(input, weight, layer_op_name, iter_time)
  File "/home/zhangziqi/Goten/python/quantize_net.py", line 78, in pre_quantize
    y_q = quantize_op(named_y, layer_op_name)
  File "/home/zhangziqi/Goten/python/quantize_net.py", line 64, in quantize_op
    return swalp_quantize(param, 8)
  File "/home/zhangziqi/Goten/python/quantize_net.py", line 49, in swalp_quantize
    max_exponent = math.floor(math.log2(max_entry))
ValueError: cannot convert float NaN to integer
Time for TrainWithBatch: 217.76080131530762 ms
Time for TrainWithBatch: 304.49581146240234 ms
```

Thanks,

**Comment by LouXiaoxuan** [comment]
@ziqi-zhang Hi, I meet the same issue, have you solved the problem ?
